BookHotelWeb/Models/Hotel.cs
namespace BookHotelWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Hotel")]
    public partial class Hotel
    {
        private List<Hotel> lineCollection = new List<Hotel>();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            Comments = new HashSet<Comment>();
            BookingDetails = new HashSet<BookingDetail>();
            Rooms = new HashSet<Room>();
        }

        [Key]
        public int IdHotel { get; set; }

        public int IdCity { get; set; }

        [StringLength(50)]
        public string HotelName { get; set; }

        [StringLength(50)]
        public string Evaluate { get; set; }

        [StringLength(50)]
        public string Distance { get; set; }

        [StringLength(500)]
        public string HotelAddress { get; set; }

        [StringLength(4000)]
        public string HotelIntroduce { get; set; }

        [StringLength(50)]
        public string CoverImage { get; set; }

        [StringLength(50)]
        public string Image1 { get; set; }

        [StringLength(50)]
        public string Image2 { get; set; }

        [StringLength(50)]
        public string Image3 { get; set; }

        [StringLength(50)]
        public string Image4 { get; set; }

        [StringLength(50)]
        public string Image5 { get; set; }

        [StringLength(50)]
        public string Image6 { get; set; }

        [StringLength(50)]
        public string Image7 { get; set; }

        [StringLength(50)]
        public string Image8 { get; set; }

        public virtual City City { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}

BookHotelWeb/Models/Room.cs
namespace BookHotelWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Room")]
    public partial class Room
    {
        [Key]
        public int IdRoom { get; set; }

        [StringLength(50)]
        public string RoomName { get; set; }

        public int? Price { get; set; }

        [StringLength(4000)]
        public string RoomService { get; set; }

        public bool? IsCheck { get; set; }

        [StringLength(4000)]
        public string RoomInformation { get; set; }

        [StringLength(4000)]
        public string RoomIntroduce { get; set; }

        public int? IdHotel { get; set; }

        public int? MaxPerson { get; set; }

        public virtual Hotel Hotel { get; set; }
    }
}

BookHotelWeb/Controllers/PartViewController.cs
using BookHotelWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookHotelWeb.Controllers
{
    public class PartViewController : Controller
    {
        private DBContext con = new DBContext();
        // GET: PartView
        public ActionResult Header()
        {
            return View();
        }
        public ActionResult Footer()
        {
            return View();
        }
        public ActionResult SearchBox()
        {
            return View();
        }
        public ActionResult NavbarAdmin()
        {
            return View();
        }


        public ActionResult HotelDialog()
        {
            return View();
        }
        public ActionResult RoomDialog()
        {
            return View();
        }
        public ActionResult Comment()
        {
            var id = Int32.Parse(Session["IdHotel"].ToString());
            ViewBag.Comments = con.Comments.Where(m => m.IdHotel == id);

            return View();
        }
    }
}

BookHotelWeb/Views/Admin/HotelEdit.cshtml
@using BookHotelWeb.Models
@model Hotel

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Tables</title>

    <!-- Custom fonts for this template -->
    <link href="~/Content/CSS/css1/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="~/Content/CSS/css1/sb-admin-2.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/Content/CSS/css1/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/Content/CSS/css1/filter.css">
    <link rel="stylesheet" href="~/Content/CSS/css1/dialog.css">
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-text mx-3">Book Hotel Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/Admin">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="" data-toggle="collapse" data-target="#table"
                   aria-expanded="true" aria-controls="table">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Table</span>
                </a>
                <div id="table" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="/Admin/HotelTable">Table Hotel</a>
                        <a class="collapse-item" href="/Admin/RoomTable">Table Room</a>
                    </div>
                </div>
            </li>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>

                </nav>
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Room information Edit</h1>
                    <!-- DataTales Example -->
                </div>
                <div class="h-content" style="margin-top:30px; position:absolute; left:500px">
                    <form  method="post">
                        <div class="h-row">
                            <label class="h-title">Hotel Id</label>
                            <input class="input-edit" type="text" name="IdHotel" value="@Model.IdHotel" />
                        </div>
                        <div class="h-row">
                            <label class="h-title">Hotel Name</label>
                            <input class="input-edit" type="text" name="HotelName" value="@Model.HotelName" />
                        </div>
                        <div class="h-row">
                            <label class="h-title">Hotel Address</label>
                            <input class="input-edit" type="text" name="HotelAddress" value="@Model.HotelAddress" />
                        </div>
                        <div class="h-row">
                            <label class="h-title">Evaluate</label>
                            <input class="input-edit" type="text" name="Evaluate" value="@Model.Evaluate" />
                        </div>
                        <div class="h-row" style="display:flex">
                            <label class="h-title" style="margin-top:20px">Hotel Introduce</label>
                            <textarea class="text-area" name="HotelIntroduce">@Model.HotelIntroduce</textarea>
                        </div>
                        <input class="h-submit" type="submit" name="name" value="Edit" />
                    </form>
                </div>
            </div>

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/CSS/css1/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/CSS/css1/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/CSS/css1/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/CSS/css1/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/CSS/css1/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/js/demo/datatables-demo.js"></script>

</body>

</html>

BookHotelWeb/Views/Admin/HotelTable.cshtml
@{
    ViewBag.Title = "Table";
}
@using BookHotelWeb.Models
@model List<Hotel>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Tables</title>

    <!-- Custom fonts for this template -->
    <link href="~/Content/CSS/css1/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    
    <!-- Custom styles for this template -->
    <link href="~/Content/CSS/css1/sb-admin-2.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/Content/CSS/css1/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/Content/CSS/css1/filter.css">
    <link href="~/Content/CSS/components/dialog.css" rel="stylesheet" />
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-text mx-3">Book Hotel Admin</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="/Admin">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="" data-toggle="collapse" data-target="#table"
                   aria-expanded="true" aria-controls="table">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Table</span>
                </a>
                <div id="table" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="/Admin/HotelTable">Table Hotel</a>
                        <a class="collapse-item" href="/Admin/RoomTable">Table Room</a>
                    </div>
                </div>
            </li>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <h1 class="h3 mb-2 text-gray-800">Hotel Table</h1>
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Table Hotel Information</h6>
                        </div>
                        <div class="card-body">
                            <div class="">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th style="text-align:center;">#</th>
                                            <th>Hotel Name</th>
                                            <th>Address</th>
                                            <th>Average price</th>
                                            <th>Room amount</th>
                                            <th>Evaluate</th>
                                            <th>Distance from city center</th>
                                            <th>Hotel description</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th></th>
                                            <th style="text-align:center;">#</th>
                                            <th>Hotel Name</th>
                                            <th>Address</th>
                                            <th>Average price</th>
                                            <th>Room amount</th>
                                            <th>Evaluate</th>
                                            <th>Distance from city center</th>
                                            <th>Hotel description</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @{ var i = 0;
                                            foreach (var hotel in Model)
                                            {
                                                <tr>
                                                    <td><input type="checkbox" name="name" value="" /></td>
                                                    <td style="text-align:center;">@(i+1)</td>
                                                    <td>@hotel.HotelName</td>
                                                    <td>@hotel.HotelAddress</td>
                                                    <td>@BookHotelWeb.Entity.Common.FormatMoney(ViewBag.AveragePrices[i].ToString()) VND</td>
                                                    <td>@ViewBag.RoomAmounts[i]</td>
                                                    <td>@hotel.Evaluate</td>
                                                    <td>@hotel.Distance</td>
                                                    <td></td>
                                                    <td class="h-action">
                                                        <a href="/Admin/HotelEdit/@hotel.IdHotel"><i class="far fa-edit"></i></a>
                                                        <a href="/Admin/DeleteHotel/@hotel.IdHotel" id="deleteHotel"><i class="fas fa-trash-alt"></i></a>
                                                        @*<div class="dialog-confirm hide-dialog">
                                                            <div class="h-title">
                                                                Delete Hotel
                                                            </div>
                                                            <div class="h-content">
                                                                <div class="h-icon">
                                                                    <div class="icon-warning">
                                                                    </div>
                                                                </div>
                                                                <div class="notify">
                                                                    Are you sure you want to delete the Hotel named : [<span style="font-weight:bold">@hotel.HotelName</span>]?
                                                                </div>
                                                            </div>
                                                            <div class="buttons">
                                                                <div class="h-btn-agree" id="agreeDelete">
                                                                    <a class="btn-confirm btn-default btn-agree" href="#">Yes</a>
                                                                </div>
                                                                <div class="h-btn-no" id="disagreeDelete">
                                                                    <a  class="btn-confirm btn-default btn-disagree" href="#">No</a>
                                                                </div>

                                                            </div>
                                                        </div>*@
                                                    </td>
                                                </tr>
                                                i += 1;
                                            }
                                        }
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->
            </div>

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/CSS/css1/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/CSS/css1/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/CSS/css1/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/CSS/css1/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/CSS/css1/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/js/demo/datatables-demo.js"></script>
    
</body>

</html>

BookHotelWeb/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin";
}


<!DOCTYPE html>
<html lang="en">

<head>
    <title>Book Hotel Admin</title>
    <!-- Custom fonts for this template-->
    <link href="~/Content/Css/css1/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/CSS/css1/sb-admin-2.css" rel="stylesheet">
    <link href="~/Content/CSS/css1/filter.css" rel="stylesheet"/>
</head>
<body id="page-top"> 
        <!-- Page Wrapper -->
        <div id="wrapper">
            @{ Html.RenderAction("NavbarAdmin", "PartView");}
        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/Css/css1/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/Css/css1/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/Css/css1/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/Js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/Css/css1/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/Js/demo/chart-area-demo.js"></script>
    <script src="~/Content/Js/demo/chart-pie-demo.js"></script>

</body>

</html>

BookHotelWeb/Views/Admin/Insert.cshtml
@{
    ViewBag.Title = "Insert";
}

<h2>Insert</h2>